bregenz-bewegt/bregenz-bewegt

- apps/client/android/app/src/main/assets/capacitor.config.json
- prisma/seed.ts
| Bug fix?             | no                                             |
| New feature?         |  yes                                             |
| Related issues/PRs   | #32 |
> Prisma Seed - New User

- libs/client/common/stores/src/lib/user.store.ts
- libs/client/common/validation/src/lib/schemas/register.ts
- libs/client/types/src/lib/index.ts
- libs/client/types/src/lib/types/index.ts
- libs/client/types/src/lib/types/login-credentials.ts
- libs/client/types/src/lib/types/register-credentials.ts
- libs/client/ui/pages/src/lib/login/login.tsx
- libs/client/ui/pages/src/lib/register/register.scss
- libs/client/ui/pages/src/lib/register/register.tsx
- libs/server/common/src/lib/validation/errors/login-error.ts
- libs/server/common/src/lib/validation/errors/register-error.ts
- libs/server/controllers/auth/src/lib/auth.service.ts
- libs/shared/types/src/lib/dto/auth/register.dto.ts
| Related issues/PRs   | #36  |
| External ticket link |  [https://trello.com/c/nfKx5AMh](https://trello.com/c/nfKx5AMh)    |
> Optional Register Fields

- libs/client/ui/pages/src/lib/profile/profile.scss
- libs/client/ui/pages/src/lib/profile/profile.tsx
| Bug fix?             | no                                             |
| Related issues/PRs   | #46 |
| External ticket link | https://trello.com/c/ZkCyIctx     |
> Username in profile

- libs/client/common/stores/src/lib/user.store.ts
- libs/client/common/validation/src/lib/schemas/forgot-password.ts
- libs/client/common/validation/src/lib/schemas/index.ts
- libs/client/common/validation/src/lib/schemas/reset-password.ts
- libs/client/ui/components/src/lib/route-guard/route-guard.tsx
- libs/client/ui/pages/src/lib/email-sent/email-sent.scss
- libs/client/ui/pages/src/lib/email-sent/email-sent.tsx
- libs/client/ui/pages/src/lib/forgot-password/forgot-password.scss
- libs/client/ui/pages/src/lib/forgot-password/forgot-password.tsx
- libs/client/ui/pages/src/lib/index.ts
- libs/client/ui/pages/src/lib/login/login.tsx
- libs/client/ui/pages/src/lib/profile/profile.tsx
- libs/client/ui/pages/src/lib/reset-password/reset-password.tsx
- libs/client/ui/router/src/index.ts
- libs/client/ui/router/src/lib/index.ts
- libs/client/ui/router/src/lib/private-tabs-outlet/private-tabs-outlet.tsx
- libs/client/ui/router/src/lib/public-outlet/public-outlet.tsx
- libs/client/ui/router/src/lib/router.tsx
- libs/client/ui/router/tsconfig.lib.json
- libs/server/controllers/auth/src/lib/auth.controller.ts
- libs/server/controllers/auth/src/lib/auth.service.ts
- libs/shared/errors/src/lib/forgot-password-error.ts
- libs/shared/errors/src/lib/index.ts
- libs/shared/types/src/lib/dto/auth/forgot-password.dto.ts
- libs/shared/types/src/lib/dto/auth/index.ts
| Related issues/PRs   | #49  |
| External ticket link | https://trello.com/c/7mp2bY9i, https://trello.com/c/N599di65, https://trello.com/c/N599di65, https://trello.com/c/N599di65, https://trello.com/c/mopL5Qpg     |
> Login forgot password

- libs/client/ui/components/src/lib/input/input.scss
- libs/client/ui/pages/src/lib/login/login.tsx
- libs/client/ui/pages/src/lib/profile/profile.scss
- libs/client/ui/pages/src/lib/profile/profile.tsx
- libs/client/ui/pages/src/lib/register/register.tsx
| Related issues/PRs   | #66  |
| External ticket link |    |
> Disable Profile Scroll when locked

- libs/client/ui/components/src/lib/park-card/park-card.scss
- libs/client/ui/components/src/lib/park-card/park-card.tsx
- libs/client/ui/pages/src/lib/profile/profile.tsx
- libs/client/ui/pages/src/lib/start/start.scss
| Related issues/PRs   | #68  |
> Park card styling

- apps/client/src/theme/variables/ionic.scss
- libs/client/ui/components/src/lib/activity-timer/activity-timer.scss
- libs/client/ui/components/src/lib/header/header.scss
| Related issues/PRs   | closes #70  |
> Darkmode bug fixes

- libs/client/ui/components/src/lib/activity-timer/activity-timer.scss
- libs/client/ui/components/src/lib/header/header.scss
- libs/client/ui/components/src/lib/header/header.tsx
- libs/client/ui/pages/src/lib/profile/profile.tsx
- libs/client/ui/router/src/lib/private-tabs-outlet/private-tabs-outlet.tsx
- libs/client/ui/router/src/lib/tabs.tsx
- package-lock.json
- package.json
| New feature?         | no|
| Related issues/PRs   | closes #25  |
> Change IonIcons to Iconsax

- libs/client/ui/pages/src/lib/profile/profile.tsx
| Related issues/PRs   | closes #76  |
| External ticket link |     |
> Changed delete account label

- libs/client/ui/pages/src/lib/leaderboard/leaderboard.scss
- libs/client/ui/pages/src/lib/leaderboard/leaderboard.tsx
- libs/client/ui/router/src/lib/private-tabs-outlet/private-tabs-outlet.tsx
| Related issues/PRs   | closes #95  |
> Leaderboard sticky self row top

- apps/client/project.json
- package.json
| Related issues/PRs   | closes #106  |
> Add IOS script to run on native IOS devices

- libs/server/controllers/leaderboard/src/lib/leaderboard.controller.ts
- libs/server/controllers/leaderboard/src/lib/leaderboard.service.ts
| Related issues/PRs   | closes #104  |
> Consider public preference option for leadboard display

- libs/client/ui/components/src/lib/input/input.scss
- libs/client/ui/components/src/lib/item-group/item-group.scss
- libs/client/ui/pages/src/lib/start/start.scss
| Related issues/PRs   | closes #102  |
> Removed borders from inputs

- libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.tsx
| Related issues/PRs   | closes #116  |
> Smooth exercise detail tab display toggle

- prisma/seed.ts
| Related issues/PRs   | closes #117  |
> Fix `deleteUnusedProfileImg()` in prisma seed

- libs/client/ui/pages/src/lib/leaderboard/leaderboard.tsx
| New feature?         | no                                            |
| Related issues/PRs   | #122  |
> Show initial Timespan filter value

- libs/client/ui/components/src/lib/coin-depot/coin-depot.scss
- libs/client/ui/components/src/lib/coin-depot/coin-depot.tsx
- libs/client/ui/pages/src/lib/login/login.tsx
- libs/client/ui/pages/src/lib/onboarding/slides/rewards/rewards.tsx
- libs/client/ui/pages/src/lib/profile/profile.scss
- libs/client/ui/pages/src/lib/profile/profile.tsx
| Bug fix?             | yes                                           |
| Related issues/PRs   | #119 #120  |
| External ticket link |     |
> Prize Draw Information

- libs/server/controllers/activity/src/lib/activity.service.ts
- prisma/migrations/20221104223150_activity_park/migration.sql
- prisma/schema.prisma
- prisma/seed.ts
| Related issues/PRs   | closes #114  |
> Added `Activity <-> Park` database relation (1:1

- libs/client/ui/components/src/lib/transition-block/transition-block.scss
| Related issues/PRs   | closes #140 |
> Remove Transition block gradient

- libs/client/ui/pages/src/lib/login/login.tsx
- libs/client/ui/pages/src/lib/park-detail/park-detail.tsx
- libs/server/controllers/auth/src/lib/auth.service.ts
- package-lock.json
- package.json
- prisma/migrations/20221114155238_guest_fingerprint/migration.sql
- prisma/schema.prisma
| Related issues/PRs   | closes #86, closes #162 |
> Assign CUIDs as usernames for guest users

- apps/client/capacitor.config.ts
| Related issues/PRs   | closes #156  |
> Add Capacitor appId

- libs/client/common/stores/src/lib/user.store.ts
- libs/client/ui/pages/src/lib/leaderboard/leaderboard.scss
- libs/client/ui/pages/src/lib/leaderboard/leaderboard.tsx
- libs/server/controllers/leaderboard/src/lib/leaderboard.service.ts
- libs/shared/types/src/lib/types/leaderboard/leaderboard.ts
- prisma/seed.ts
| Related issues/PRs   | #166  |
> Show profile pictures in leaderboard

- libs/client/ui/components/src/lib/quick-filter/quick-filter.scss
- libs/client/ui/components/src/lib/quick-filter/quick-filter.tsx
- libs/client/ui/pages/src/lib/park-detail/park-detail.scss
- libs/client/ui/pages/src/lib/park-detail/park-detail.tsx
| Bug fix?             | no yes                                             |
| New feature?         | no yes                                             |
| Related issues/PRs   | closes #150  |
> Change park detail filter

- libs/client/common/stores/src/lib/user.store.ts
- libs/client/ui/components/src/lib/header/header.tsx
- libs/client/ui/pages/src/lib/analytics/analytics.tsx
- libs/client/ui/pages/src/lib/leaderboard/leaderboard.tsx
- libs/client/ui/pages/src/lib/profile/friends/add-friend-modal/add-friend-modal.tsx
- libs/client/ui/pages/src/lib/profile/friends/friend-list/friend-list.tsx
- libs/client/ui/pages/src/lib/profile/friends/request-list/request-list.tsx
- libs/client/ui/pages/src/lib/profile/profile.tsx
- libs/server/common/src/lib/interceptors/index.ts
- libs/server/common/src/lib/interceptors/map-user.interceptor.ts
- libs/server/common/src/lib/interceptors/remove-sensitive-fields.interceptor.ts
- libs/server/controllers/auth/src/lib/auth.controller.ts
- libs/server/controllers/friend/src/lib/friend.controller.ts
- libs/server/controllers/user/src/lib/user.controller.ts
| Related issues/PRs   | closes #195 |
> Analytics load bug `onIonViewWillEnter` taking 0

- libs/client/ui/pages/src/lib/analytics/analytics.tsx
| Related issues/PRs   | closes #192 |
> Capitalize type syntax

- libs/server/common/src/lib/interceptors/map-profile-picture-path.interceptor.ts
- libs/server/common/src/lib/interceptors/remove-sensitive-fields.interceptor.ts
| Related issues/PRs   | closes #200 |
> `RemoveSensitiveFieldsInterceptor` mapping nested arrays of objects

- apps/client/src/theme/variables/ionic.scss
- libs/client/types/src/lib/enums/difficulty-color.ts
- libs/client/types/src/lib/enums/index.ts
- libs/client/ui/components/src/lib/difficulty-badge/difficulty-badge.tsx
- libs/client/ui/components/src/lib/quick-filter/quick-filter-option.ts
- libs/client/ui/components/src/lib/quick-filter/quick-filter.tsx
- libs/client/ui/pages/src/lib/park-detail/park-detail.tsx
| Bug fix?             | no yes                                             |
| New feature?         | no yes                                             |
| Related issues/PRs   | closes #174   |
> Change difficulty color

- libs/client/ui/components/src/lib/park-card/park-card.scss
- libs/client/ui/pages/src/lib/start/list/list.scss
- libs/client/ui/pages/src/lib/start/list/list.tsx
| Related issues/PRs   | closes #194, closes #205 |
> Add searchbar bottom whitespace

- libs/client/ui/pages/src/lib/profile/profile.tsx
| Related issues/PRs   | closes #223 |
> Delete account confirmation message to informal wording

- libs/client/ui/components/src/lib/activity-timer/activity-timer.tsx
| Related issues/PRs   | closes #219, closes #168 |
> Exercise lock information for guests

- libs/client/ui/components/src/lib/park-card/park-card.scss
- prisma/seed.purge.ts
- prisma/seed.ts
| New feature?         | no                                              |
| Related issues/PRs   | closes #234, closes #237 |
> Reset start page image max height & delete notifcations in prisma seed

- package.json
| Related issues/PRs   | closes #242 |
> Add homepage attribute

- apps/client/project.json
- apps/client/src/.htaccess
| Related issues/PRs   | closes #244 |
> Add htaccess config

- libs/client/ui/pages/src/lib/start/start.scss
| Related issues/PRs   | closes #254 |
> Reduce top whitespace on start page tab

- apps/client/src/main.tsx
- package-lock.json
- package.json
| Related issues/PRs   | closes #253 |
> Fix QR reader browser support using webrtc

- libs/client/ui/pages/src/lib/profile/friends/friend-list/friend-list.tsx
- libs/server/controllers/friend/src/lib/friend.controller.ts
| Related issues/PRs   | closes #246  |
> Fix custom friend list profile picture

- apps/client/src/main.tsx
| Related issues/PRs   | closes #257 |
> Import webrtc adapter

- libs/client/ui/pages/src/lib/scan/scan.tsx
| Related issues/PRs   | closes #259 |
> Add react qr reader facing mode

- libs/client/ui/components/src/lib/exercise-card/exercise-card.tsx
- libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.tsx
- libs/client/ui/pages/src/lib/park-detail/park-detail.tsx
| Related issues/PRs   | closes #250, closes #251 |
> Add detail page loaders

- libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.scss
- libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.tsx
| Related issues/PRs   | closes #264, closes #267 |
> Show earned points when finishing exercise

- apps/client/src/theme/styles/index.scss
- apps/client/src/theme/styles/ion-header.scss
- apps/client/src/theme/styles/ion-tab-bar.scss
- libs/client/ui/pages/src/lib/competitor-profile/competitor-profile.tsx
- libs/client/ui/pages/src/lib/notifications/notifications.tsx
- libs/client/ui/pages/src/lib/profile/appearance/appearance.tsx
- libs/client/ui/pages/src/lib/profile/difficulty/difficulty.tsx
- libs/client/ui/pages/src/lib/profile/email/email.tsx
- libs/client/ui/pages/src/lib/profile/friends/add-friend-modal/add-friend-modal.tsx
- libs/client/ui/pages/src/lib/profile/friends/friends.tsx
- libs/client/ui/pages/src/lib/profile/password/password.tsx
- libs/client/ui/pages/src/lib/profile/public-profile/public-profile.tsx
- libs/client/ui/router/src/lib/private-tabs-outlet/private-tabs-outlet.tsx
| New feature?         | yes|
| Related issues/PRs   | closes #203, closes #278 |
> Custom header 

- libs/client/ui/components/src/lib/park-card/park-card.scss
| Related issues/PRs   | #288|
> Reduce park card font size

- libs/client/ui/components/src/lib/coin-depot/coin-depot.tsx
- libs/client/ui/pages/src/lib/onboarding/slides/earn/earn.tsx
| Related issues/PRs   | closes #134  |
> Rename coin to B-Buck for consistency

- libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.tsx
| Related issues/PRs   | #302 |
> Rename muskels header on exercise detail

- libs/server/controllers/friend/src/lib/friend.service.ts
| Related issues/PRs   | closes #310 |
> Forbid friendship with unverified users

- libs/client/ui/pages/src/lib/register/register.tsx
| Bug fix?             | no                                             |
| New feature?         | no                                             |
| Related issues/PRs   |  #325 |
> Remove ToS note on register page

- libs/client/ui/components/src/lib/title-banner/title-banner.tsx
- libs/client/ui/pages/src/lib/onboarding/slides/earn/earn.tsx
| Related issues/PRs   | closes #331  |
> Rename reward coin mentions

- libs/client/ui/pages/src/lib/scan/scan.tsx
| Related issues/PRs   | closes #329 |
> Fix Mirror QR Scan camera

- libs/client/ui/pages/src/lib/analytics/analytics.tsx
| New feature?         | no                                             |
| Related issues/PRs   |closes #327 |
> Rewrite analytics guest lock hint

- libs/client/ui/components/src/lib/index.ts
- libs/client/ui/components/src/lib/role-route-guard/role-route-guard.tsx
- libs/client/ui/components/src/lib/route-guard/route-guard.scss
- libs/client/ui/router/src/lib/private-tabs-outlet/private-tabs-outlet.tsx
| New feature?         | no                                             |
| Related issues/PRs   | closes #319 |
> Redirect guest forbidden routes
